"use client";

import { useActionState } from "react";
import { FormError, FormNotice, Input, SubmitButton } from "@/components/form";
import type { PublishStatus, Sponsor } from "@/lib/supabase/types";
import { createSponsor, setSponsorStatus, type SponsorAdminState } from "./actions";

const EMPTY: SponsorAdminState = {};
const STATUSES: PublishStatus[] = ["draft", "review", "published", "archived"];

export function SponsorsAdmin({ sponsors }: { sponsors: Sponsor[] }) {
  const [createState, createAction, createPending] = useActionState(createSponsor, EMPTY);
  const [statusState, statusAction, statusPending] = useActionState(setSponsorStatus, EMPTY);
  return <div className="grid gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:gap-14"><section><h2 className="font-display text-xl font-bold">Sponsors ({sponsors.length})</h2>{sponsors.length === 0 ? <p className="mt-5 rounded-2xl border border-dashed border-black/15 px-5 py-8 text-center text-[13px] text-primary/45">No sponsors yet.</p> : <ul className="mt-5 space-y-3">{sponsors.map((sponsor) => <li key={sponsor.id} className="rounded-[24px] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-display text-base font-bold">{sponsor.name}</h3><p className="mt-1 text-[12px] text-primary/50">{sponsor.tier || "Partner"}{sponsor.website ? ` · ${sponsor.website}` : ""}</p></div><span className="rounded-full bg-black/[0.05] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-primary/60">{sponsor.status}</span></div><form action={statusAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="sponsor_id" value={sponsor.id} /><label className="text-[12px] font-semibold text-primary">Status<select name="status" defaultValue={sponsor.status} className="mt-1.5 block rounded-xl border border-black/15 bg-white px-3 py-2 text-[13px]">{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><SubmitButton pending={statusPending}>Save status</SubmitButton></form></li>)}</ul>}</section><section><h2 className="font-display text-xl font-bold">Add a sponsor</h2><form action={createAction} className="mt-5 rounded-[28px] bg-white p-7"><div className="space-y-5"><FormError message={createState.error || statusState.error} /><FormNotice message={createState.notice || statusState.notice} /><Input label="Name" name="name" required placeholder="Sponsor or partner name" /><Input label="Slug" name="slug" hint="Leave blank to derive it from the name." /><Input label="Tier" name="tier" placeholder="Principal partner" /><Input label="Logo path" name="logo_path" placeholder="/brand/partner-logo.png" /><Input label="Website" name="website" type="url" placeholder="https://example.org" /><label className="block text-[13px] font-semibold text-primary">Initial status<select name="status" defaultValue="draft" className="mt-2 block w-full rounded-2xl border border-black/15 bg-white px-4 py-3 text-[14px]">{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><SubmitButton pending={createPending}>Save sponsor</SubmitButton></div></form></section></div>;
}
