"use client";

import { useActionState } from "react";
import { FormError, FormNotice, Input, SubmitButton, Textarea } from "@/components/form";
import type { Download, Faq, PublishStatus } from "@/lib/supabase/types";
import { createDownload, createFaq, setDownloadStatus, setFaqStatus, type ContentAdminState } from "./actions";

const EMPTY: ContentAdminState = {};
const STATUSES: PublishStatus[] = ["draft", "review", "published", "archived"];

export function ContentAdmin({ faqs, downloads }: { faqs: Faq[]; downloads: Download[] }) {
  const [faqCreate, faqCreateAction, faqCreatePending] = useActionState(createFaq, EMPTY);
  const [faqStatus, faqStatusAction, faqStatusPending] = useActionState(setFaqStatus, EMPTY);
  const [downloadCreate, downloadCreateAction, downloadCreatePending] = useActionState(createDownload, EMPTY);
  const [downloadStatus, downloadStatusAction, downloadStatusPending] = useActionState(setDownloadStatus, EMPTY);
  return <div className="space-y-14">
    <section><h2 className="font-display text-xl font-bold">FAQs ({faqs.length})</h2>{faqs.length ? <ul className="mt-5 space-y-3">{faqs.map((faq) => <li key={faq.id} className="rounded-[24px] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="max-w-2xl font-display text-base font-bold">{faq.question}</h3><span className="rounded-full bg-black/[0.05] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-primary/60">{faq.status}</span></div><form action={faqStatusAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="faq_id" value={faq.id} /><label className="text-[12px] font-semibold text-primary">Status<select name="status" defaultValue={faq.status} className="mt-1.5 block rounded-xl border border-black/15 bg-white px-3 py-2 text-[13px]">{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><SubmitButton pending={faqStatusPending}>Save status</SubmitButton></form></li>)}</ul> : <p className="mt-5 text-[13px] text-primary/45">No managed FAQs yet. The public page is using its approved fallback copy.</p>}<form action={faqCreateAction} className="mt-6 rounded-[28px] bg-white p-7"><h3 className="font-display text-lg font-bold">Add FAQ</h3><div className="mt-5 space-y-5"><FormError message={faqCreate.error || faqStatus.error} /><FormNotice message={faqCreate.notice || faqStatus.notice} /><Input label="Question" name="question" required /><Textarea label="Answer" name="answer" required rows={4} /><Input label="Category" name="category" placeholder="Registration" /><label className="block text-[13px] font-semibold text-primary">Initial status<select name="status" defaultValue="draft" className="mt-2 block w-full rounded-2xl border border-black/15 bg-white px-4 py-3 text-[14px]">{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><SubmitButton pending={faqCreatePending}>Save FAQ</SubmitButton></div></form></section>
    <section><h2 className="font-display text-xl font-bold">Downloads ({downloads.length})</h2>{downloads.length ? <ul className="mt-5 space-y-3">{downloads.map((download) => <li key={download.id} className="rounded-[24px] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-display text-base font-bold">{download.title}</h3><p className="mt-1 break-all text-[12px] text-primary/50">{download.file_url}</p></div><span className="rounded-full bg-black/[0.05] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-primary/60">{download.status}</span></div><form action={downloadStatusAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="download_id" value={download.id} /><label className="text-[12px] font-semibold text-primary">Status<select name="status" defaultValue={download.status} className="mt-1.5 block rounded-xl border border-black/15 bg-white px-3 py-2 text-[13px]">{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><SubmitButton pending={downloadStatusPending}>Save status</SubmitButton></form></li>)}</ul> : <p className="mt-5 text-[13px] text-primary/45">No published rules or downloads yet.</p>}<form action={downloadCreateAction} className="mt-6 rounded-[28px] bg-white p-7"><h3 className="font-display text-lg font-bold">Add download</h3><div className="mt-5 space-y-5"><FormError message={downloadCreate.error || downloadStatus.error} /><FormNotice message={downloadCreate.notice || downloadStatus.notice} /><Input label="Title" name="title" required placeholder="Rules and Regulations" /><Textarea label="Description" name="description" rows={3} /><Input label="Version" name="version" placeholder="2026.1" /><Input label="File URL" name="file_url" required placeholder="/downloads/rules-2026.pdf" hint="Use a site path or HTTPS URL to a reviewed file." /><Input label="File size in bytes" name="file_size_bytes" type="number" min="1" /><label className="block text-[13px] font-semibold text-primary">Initial status<select name="status" defaultValue="draft" className="mt-2 block w-full rounded-2xl border border-black/15 bg-white px-4 py-3 text-[14px]">{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><SubmitButton pending={downloadCreatePending}>Save download</SubmitButton></div></form></section>
  </div>;
}
