"use client";

import { useActionState } from "react";
import { FormError, FormNotice, Input, SubmitButton, Textarea } from "@/components/form";
import type { GalleryContentType, GalleryItem, PublishStatus } from "@/lib/supabase/types";
import { createGalleryItem, setGalleryStatus, type GalleryAdminState } from "./actions";

const EMPTY: GalleryAdminState = {};
const STATUSES: PublishStatus[] = ["draft", "review", "published", "archived"];
const CONTENT_TYPES: GalleryContentType[] = ["event", "school", "student", "people", "venue", "press"];
const CONTENT_LABELS: Record<GalleryContentType, string> = { event: "Event", school: "School", student: "Student", people: "People", venue: "Venue", press: "Press" };

export function GalleryAdmin({ items, lgas, stages }: { items: GalleryItem[]; lgas: { id: string; name: string }[]; stages: { id: string; name: string; ordinal: number }[] }) {
  const [createState, createAction, createPending] = useActionState(createGalleryItem, EMPTY);
  const [statusState, statusAction, statusPending] = useActionState(setGalleryStatus, EMPTY);
  return <div className="grid gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:gap-14">
    <section><h2 className="font-display text-xl font-bold">Gallery items ({items.length})</h2>{items.length === 0 ? <p className="mt-5 rounded-2xl border border-dashed border-black/15 px-5 py-8 text-center text-[13px] text-primary/45">No gallery items yet.</p> : <ul className="mt-5 space-y-3">{items.map((item) => <li key={item.id} className="rounded-[24px] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-display text-base font-bold">{item.title || "Untitled image"}</h3><p className="mt-1 break-all text-[12px] text-primary/50">{item.image_path}</p><p className="mt-2 text-[11px] text-primary/50">{CONTENT_LABELS[item.content_type]}{item.lga_id ? ` · LGA tagged` : ""}{item.stage_id ? " · Stage tagged" : ""}</p></div><span className="rounded-full bg-black/[0.05] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-primary/60">{item.status}</span></div><form action={statusAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="gallery_id" value={item.id} /><label className="text-[12px] font-semibold text-primary">Status<select name="status" defaultValue={item.status} className="mt-1.5 block rounded-xl border border-black/15 bg-white px-3 py-2 text-[13px]">{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><SubmitButton pending={statusPending}>Save status</SubmitButton></form></li>)}</ul>}</section>
    <section><h2 className="font-display text-xl font-bold">Add a photograph</h2><form action={createAction} className="mt-5 rounded-[28px] bg-white p-7"><div className="space-y-5"><FormError message={createState.error || statusState.error} /><FormNotice message={createState.notice || statusState.notice} /><Input label="Image path" name="image_path" required placeholder="/img/meeting-group.jpg" hint="Use a reviewed public asset path or a Supabase public image URL." /><Input label="Title" name="title" placeholder="Principals across the district" /><Textarea label="Caption" name="caption" rows={3} /><label className="block text-[13px] font-semibold text-primary">Content type<select name="content_type" defaultValue="event" className="mt-2 block w-full rounded-2xl border border-black/15 bg-white px-4 py-3 text-[14px]">{CONTENT_TYPES.map((type) => <option key={type} value={type}>{CONTENT_LABELS[type]}</option>)}</select></label><label className="block text-[13px] font-semibold text-primary">LGA (optional)<select name="lga_id" defaultValue="" className="mt-2 block w-full rounded-2xl border border-black/15 bg-white px-4 py-3 text-[14px]"><option value="">No LGA tag</option>{lgas.map((lga) => <option key={lga.id} value={lga.id}>{lga.name}</option>)}</select></label><label className="block text-[13px] font-semibold text-primary">Stage (optional)<select name="stage_id" defaultValue="" className="mt-2 block w-full rounded-2xl border border-black/15 bg-white px-4 py-3 text-[14px]"><option value="">No stage tag</option>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.ordinal}. {stage.name}</option>)}</select></label><Input label="Display order" name="sort_order" type="number" defaultValue="0" /><label className="block text-[13px] font-semibold text-primary">Initial status<select name="status" defaultValue="draft" className="mt-2 block w-full rounded-2xl border border-black/15 bg-white px-4 py-3 text-[14px]">{STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><SubmitButton pending={createPending}>Save photograph</SubmitButton></div></form></section>
  </div>;
}
